language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
matrix:
  allow_failures:
    - rvm: 1.9.3
before_install:
  - "rm -rf Gemfile.lock"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bundle exec rspec spec
after_script:
  - "bundle exec cucumber features"