language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
matrix:
  allow_failures:
    - rvm: 2.0.0
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bundle exec rspec spec
